using System.ComponentModel.DataAnnotations;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week8_Validation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }

        [Required] //Without error message, an error message will be made for you
        [StringLength(1000, ErrorMessage = "Name must be at least 2 characters", MinimumLength = 2)]
        [Display(Name = "First name")]
        public string First_name { get; set; }

        [Required] //Because this field in the database is NOT NULL, it's wise to make this required
        [Display(Name = "Last name")]
        public string Last_name { get; set; }

        [Required(ErrorMessage = "Student number required")] //Here you can customize the error message
        [Display(Name = "Student number")]
        public string s_number { get; set; }

        [DataType(DataType.Date)]//DataType is used to format the type of input on the view. In this case, this annotation will generation an input tag with type=date.
        public Nullable<System.DateTime> dob { get; set; }
    }
}
