//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty
    {
        public int Id { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
        public Nullable<int> Program_Id { get; set; }
    
        public virtual Program Program { get; set; }
    }
}
