//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week9_Authorization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructors
    {
        public Instructors()
        {
            this.Programs1 = new HashSet<Programs>();
        }
    
        public int Id { get; set; }
        public string F_name { get; set; }
        public string L_name { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public Nullable<int> Program_id { get; set; }
    
        public virtual Programs Programs { get; set; }
        public virtual ICollection<Programs> Programs1 { get; set; }
    }
}
